Table teams {
  number smallint [not null]
  name text [not null]
  created_at timestamptz [not null]

  indexes {
    number [pk] // patch: include (name)
  }

  Note: 'A team utilizing the platform'
}

Table users {
  id uuid [not null]
  name text [not null]
  created_at timestamptz [not null]

  indexes {
    id [pk] // patch: include (name)
  }

  Note: 'A user of the platform'
}

Table team_users {
  user_id uuid [not null]
  team_num smallint [not null]
  added_by uuid
  added_at timestamptz [not null]

  indexes {
    user_id [pk] // patch: include (team_num)
    (team_num, user_id) [unique]
    (team_num, added_at) // order by time added
    added_by // for fk
  }

  Note: 'A user\'s association with a team'
}
Ref: team_users.user_id > users.id [delete: cascade]
Ref: team_users.team_num > teams.number [delete: cascade]
Ref: team_users.added_by > users.id [delete: set null]

Table team_requests {
  user_id uuid [not null]
  team_num smallint [not null]
  requested_at timestamptz [not null]

  indexes {
    user_id [pk]
    (team_num, requested_at) // order by time requested, patch: include (user_id)
  }

  Note: 'A user\'s request to join a team'
}
Ref: team_requests.user_id > users.id [delete: cascade]
Ref: team_requests.team_num > teams.number [delete: cascade]

Table disabled_users {
  user_id uuid [not null]
  disabled_by uuid [not null]
  disabled_at timestamptz [not null]

  indexes {
    user_id [pk]
    disabled_by // for fk
  }

  Note: 'A user whose privileges have been temporarily revoked'
}
Ref: disabled_users.user_id > users.id [delete: cascade]
Ref: disabled_users.disabled_by > users.id [delete: cascade]

Table permission_types {
  id citext [not null]
  name text [not null]
  description text [not null]

  indexes {
    id [pk]
  }

  Note: 'Types of permissions users may hold'
}

Table permissions {
  user_id uuid [not null]
  type citext [not null]
  team_num smallint [not null]
  granted_by uuid
  granted_at timestamptz [not null]

  indexes {
    (user_id, type) [pk]
    (team_num, type)
    (team_num, user_id) // for fk
    (team_num, granted_by) // for fk
  }

  Note: 'A user\'s permission'
}
Ref: permissions.user_id > users.id [delete: cascade]
Ref: permissions.type > permission_types.id [delete: cascade]
Ref: permissions.(team_num, user_id) > team_users.(team_num, user_id) [delete: cascade]
Ref: permissions.(team_num, granted_by) > team_users.(team_num, user_id) [delete: cascade]
