Table question_types {
  id citext [not null]
  name text [not null]
  description text [not null]

  indexes {
    id [pk]
  }

  Note: 'A type of scouting question shown to the user'
}

Table categories {
  id citext [not null]
  has_match bool [not null]

  indexes {
    id [pk]
  }

  Note: 'A type of scouting data users can submit'
}

Table question_sections {
  id uuid [not null]
  season smallint [not null]
  category citext [not null]
  index smallint [not null]
  name text [not null]

  indexes {
    id [pk]
    (season, category, index) [unique]
  }

  Note: 'A section within a set of scouting questions'
}
Ref: question_sections.category > categories.id [delete: restrict]

Table questions {
  id uuid [not null]
  section_id uuid [not null]
  index smallint [not null]
  prompt text [not null]
  type citext [not null]
  config jsonb [not null, default: '{}']
  info_filepath text

  indexes {
    id [pk]
  }

  Note: 'A scouting question that users must answer'
}
Ref: questions.section_id > question_sections.id
Ref: questions.type > question_types.id [delete: restrict]

Table submissions {
  id uuid [not null]
  category citext [not null]
  season smallint [not null]
  event_code citext [not null]
  match_key citext
  team_num smallint [not null]
  scouted_by uuid
  scouted_for smallint
  created_at timestamptz [not null]

  indexes {
    id [pk]
  }

  Note: 'A scouting data submission'
}
Ref: submissions.category > categories.id [delete: restrict]
Ref: submissions.(season, event_code) > frc_events.(season, code) [delete: restrict]
Ref: submissions.match_key > frc_matches.key [delete: restrict]
Ref: submissions.season > frc_seasons.year [delete: restrict]
Ref: submissions.(season, team_num) > frc_teams.(season, number) [delete: restrict]
Ref: submissions.scouted_by > users.id [delete: set null]
Ref: submissions.scouted_for > teams.number [delete: set null]

Table submission_data {
  submission_id uuid [not null]
  question_id uuid [not null]
  value text [not null]

  indexes {
    (submission_id, question_id) [pk]
  }

  Note: 'A submission\'s scouting data'
}
Ref: submission_data.submission_id > submissions.id [delete: cascade]
Ref: submission_data.question_id > questions.id [delete: restrict]
