Table sync.tba_pull_etags {
  data_pulled_at timestamptz [not null]
  endpoint text [not null]
  etag text [not null]

  indexes {
    endpoint [pk] // patch: include value
  }
}

Table sync.nexus_push_times {
  data_as_of timestamptz [not null]
  event_key citext [not null]

  indexes {
    event_key [pk]
  }
}
Ref: sync.nexus_push_times.event_key > frc_events.key [delete: cascade]
