CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA extensions;

CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;
GRANT USAGE ON SCHEMA cron TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cron TO postgres;

CREATE EXTENSION IF NOT EXISTS btree_gin WITH SCHEMA extensions;

CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;
